:PROPERTIES:
:ID:       23362f82-a040-4316-b238-3989ddb0c6f5
:END:
#+TITLE: SLinux Trouble Should Denials
#+CREATED: [2022-12-31 Sat 16:29]
#+LAST_MODIFIED: [2022-12-31 Sat 16:46]
#+filetags: linux selinux
* How to trouble shoot SELInux denials :selinux::linux:
A lot of people's problems with selinux is it will block something they are trying to do.
So then they just disable it. That is fine for a personal machine but what if it is a server and you want it to work?

** ~ausearch~ command
~ausearch~ can query the ~auditd~ logs based on search criteria.

*** Find recent events
Recent will grab the last ten minutes
#+begin_src shell
ausearch -m avc --start recent
#+end_src

Find issues from today looking for sshd
#+begin_src shell
ausearch -m avc --start today | grep sshd
#+end_src



*** Options
Most used options from the man-page
You can fine the online man-page [[https://man7.org/linux/man-pages/man8/ausearch.8.html][here]].
#+begin_example
       -a, --event audit-event-id
              Search for an event based on the given event ID. Messages
              always start with something like
              msg=audit(1116360555.329:2401771). The event ID is the
              number after the ':'. All audit events that are recorded
              from one application's syscall have the same audit event
              ID. A second syscall made by the same application will
              have a different event ID. This way they are unique.

        --format option
              Events that match the search criteria are formatted using
              this option. The supported formats are: raw, default,
              interpret, csv, and text. The raw option is described
              under the --raw command line option. The default option is
              what you get when no formatting options are passed. It
              includes one line as a visual separator which indicates
              the time stamp and then the records of the event follow.
              The interpret option is explained under the -i command
              line option. The csv option outputs the results of the
              search as a normalized event in comma separated value
              (CSV) format suitable for import into analytical programs.
              The text option turns the event into an English sentence
              that is easier to understand than other options, but it
              comes at the expense of loss of detail. In most cases this
              is perfectly fine since the original event still retains
              all the original information.

        -m, --message message-type | comma-sep-message-type-list
              Search for an event matching the given message type.
              (Message types are also known as record types.) You may
              also enter a comma separated list of message types or
              multiple individual message types each with its own -m
              option. There is an ALL message type that doesn't exist in
              the actual logs. It allows you to get all messages in the
              system. The list of valid messages types is long. The
              program will display the list whenever no message type is
              passed with this parameter. The message type can be either
              text or numeric. If you enter a list, there can be only
              commas and no spaces separating the list.

        -ts, --start [start-date] [start-time]
              Search for events with time stamps equal to or after the
              given start time. The format of start time depends on your
              locale. You can check the format of your locale by running
              date '+%x'.  If the date is omitted, today is assumed. If
              the time is omitted, midnight is assumed. Use 24 hour
              clock time rather than AM or PM to specify time. An
              example date using the en_US.utf8 locale is 09/03/2009. An
              example of time is 18:00:00. The date format accepted is
              influenced by the LC_TIME environmental variable.

              You may also use the word: now, recent, boot, today,
              yesterday, this-week, week-ago, this-month, this-year, or
              checkpoint. Boot means the time of day to the second when
              the system last booted. Today means starting at 1 second
              after midnight. Recent is 10 minutes ago. Yesterday is 1
              second after midnight the previous day. This-week means
              starting 1 second after midnight on day 0 of the week
              determined by your locale (see localtime). Week-ago means
              starting 1 second after midnight exactly 7 days ago.
              This-month means 1 second after midnight on day 1 of the
              month. This-year means the 1 second after midnight on the
              first day of the first month.

              checkpoint means ausearch will use the timestamp found
              within a valid checkpoint file ignoring the recorded
              inode, device, serial, node and event type also found
              within a checkpoint file. Essentially, this is the
              recovery action should an invocation of ausearch with a
              checkpoint option fail with an exit status of 10, 11 or
              12. It could be used in a shell script something like:

                   ausearch --checkpoint /etc/audit/auditd_checkpoint.txt -i
                   _au_status=$?
                   if test ${_au_status} eq 10 -o ${_au_status} eq 11 -o ${_au_status} eq 12
                   then
                     ausearch --checkpoint /etc/audit/auditd_checkpoint.txt --start checkpoint -i
                   fi


#+end_example

** ~audit2why~
~audit2why~ will translate audit messages into a description of why it was denied.

*** Search for sshd issues and find out why
This command will search for issues starting today for sshd with grep then pipe it into ~audit2why~ and possibly get an explanation.
#+begin_src shell
ausearch -m avc --start today | grep sshd | audit2why
#+end_src
