:PROPERTIES:
:ID:       81d62666-4ce8-4244-b498-739a680f9673
:ROAM_TAGS: sqli hacking
:END:
#+title: SQL Injection
#+SETUPFILE: /home/unseen/Documents/Notes/org/roam/org-setup.org

#+CREATED: [2022-12-17 12:03:14]
#+LAST_MODIFIED: [2023-05-26 Fri 21:50]

* SQL Injection :injection:sqli::cybersec::sql:
SQL injection is a type of attack in which an attacker inserts malicious SQL code into an application's input in order to gain unauthorized access to sensitive data in the database or to manipulate data. This can allow the attacker to read sensitive data, modify or delete data, execute administrative tasks on the database, and even issue commands to the operating system. SQL injection attacks are commonly used against PHP and ASP applications, but are less common in J2EE and ASP.NET applications due to the nature of their programmatic interfaces. The severity of an SQL injection attack is high, as it can have significant consequences ranging from data disclosure and tampering to system destruction. Defense measures, such as using low privilege connections to the database and implementing input validation, can help reduce the risk of successful SQL injection attacks.

It can happen when:
1. untrusted data enters the program
2. The data is used to create an SQL query.

   There are a few forms of injection

   + Second Order

   + Error Based

   + Blind Injection

   + Union Based
** Error Based
Error Based SQL injection is a [[id:a49c4f35-2e27-42e2-8eea-310b5f2ec352][in-band]] injection technique.
These types of injections are where you force the database to generate an error.
Using these error messages returning you can use to get the structure of the database or even the entire database.

** Union Based
Union Injection is where you use the SQL ~union~ operator. This combines multiple fields into a single result to be displayed.
** Blind SQL Injection
Blind Sqli is when you ask the database true or false question's and determin the Answer based on the application's response.
This attack is used when the application shows generic errors but still is vulnerable to injection.
It is almost identical, but here you ask true or false questions.
They are also as common as other forms. They give a false sense of security.
They are much harder and longer to do by hand

The best analogy to it is playing 20 questions with the database
*** Examples
There are a few ways to verify blind sql injections

**** Boolean Based
Using a page with shows a article with a given id, you may preform a couple of tests.
#+begin_example
http://newspaper.com/items.php?id=2
#+end_example

The server may send a query that looks like
#+begin_src sql
SELECT title, description, body FROM items WHERE ID = 2
#+end_src

You may try and inject something that will return true.
Some examples of things that always return true
+ AND 1=1
+ OR 1=1
#+begin_example
http://newspaper.com/items.php?id=2 and 1=1
#+end_example
If the content that returns true if different from false, you are able  to continue.
There isn't much stopping either then privileges setup and different sql syntax's.

**** Time Based
This Method relies on the database pausing for a set amount of time then returning results.

If the first letter of the db name is A, wait 10 seconds
If the first letter of the db name is B, wait 10 seconds, etc.
You should see if SQlmap is able to detect the injection, but it is sensitive to time.
***** MicroSoft SQL server
#+begin_example
http://www.site.com/vulnerable.php?id=1' waitfor delay '00:00:10'--
#+end_example
***** MySQL
Here us an example, this depends on the performance of the server.
#+begin_example
BENCHMARK(5000000,ENCODE('MSG','by 5 seconds'))

#+end_example

Another example
#+begin_example
1 UNION SELECT IF(SUBSTRING(user_password,1,1) = CHAR(50),BENCHMARK(5000000,ENCODE('MSG','by 5 seconds')),null) FROM users WHERE user_id = 1;
#+end_example


** Second order Injection
A Second order injection is where user passed data is stored for later use by the database. The SQL Injection is then triggered by a different action on the webpage.


** Tools
+ [[id:ef03bc97-55a3-44e6-b24a-523630f0090d][SQLMap]]
** Links to check out

+ https://www.blackhat.com/presentations/bh-usa-04/bh-us-04-hotchkies/bh-us-04-hotchkies.pdf
+ https://owasp.org/www-community/attacks/Blind_SQL_Injection
+ https://owasp.org/www-community/attacks/SQL_Injection
+ https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF
