:PROPERTIES:
:ID:       e32a3fd4-d13c-4274-be79-69c688f79398
:END:
#+TITLE: Cookie Bugs
#+SETUPFILE: /home/unseen/Documents/Notes/org/roam/org-setup.org
#+CREATED: [2023-05-27 Sat 17:27]
#+LAST_MODIFIED: [2023-07-10 Mon 05:22]
* Cookie Bugs
Cookies are how your web browser can tell a web server who they are, they are sent from the server to your browser.
They handle things like sign-in and shopping carts, and much more.

When the server responds with a response with ~Set-Cookie name=val~, on further request the agent will respond with that cookie.



Cookies can be sent to subdomains too if they have the ~domain~ attribute, they may also be sent to parent domains if the attribute is ~.example.com~ as an example.


** Prefixed cookies and cookie scope
*** Domain
Domain states the scope of a cookie, by saying what hosts are allowed to access the cookie.
subdomain cookies are allowed, so Domain is less restrictive.
Setting ~Domain=example.com~ will allow ~sub.example.com~ share the cookie.

*** Path
Path stats that a url path must exists in the url, ~%x2F~ also counts as a directory separator.

Setting it to ~/Foo~ means every sub directory of foo can share the cookie.

*** SaneSite
From Mozilla Docs:

The [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value][=SameSite=]] attribute lets servers specify whether/when cookies are sent with cross-site requests (where [[https://developer.mozilla.org/en-US/docs/Glossary/Site][Site]] is defined by the registrable domain and the /scheme/ : http or https). This provides some protection against cross-site request forgery attacks [[id:4312a6c1-a0e8-42b3-8f63-16de99ec3f39][Cross Site request forgery]](). It takes three possible values: =Strict=, =Lax=, and =None= .

With =Strict=, the browser only sends the cookie with requests from the cookie's origin site. =Lax= is similar, except the browser also sends the cookie when the user /navigates/ to the cookie's origin site (even if the user is coming from a different site). For example, by following a link from an external site. =None= specifies that cookies are sent on both originating and cross-site requests, but /only in secure contexts/ (i.e., if ~SameSite=None~ then the =Secure= attribute must also be set). If no =SameSite= attribute is set, the cookie is treated as =Lax=.
*** __Secure
Cookies with ~__Secure~ prefix are used for https pages also needs to have the ~secure~ flag.
The cookie can only be used with HTTPS pages, it is also inaccessible to javascript which helps against [[id:524a19f0-d6e9-4785-9f8d-262495410c08][XSS]].

*** __Host
Cookies with the ~__Host~ prefix are not able to have a domain specified and are not sent to subdomains.
The path for the cookie must also be ~/~
