#+property: header-args :emacs-lisp
:PROPERTIES:
:ROAM_TAGS: script emacs roam org
:END:
#+title: Publish Org Roam

#+CREATED: [2022-12-17 12:03:14]
#+LAST_MODIFIED: [2023-06-30 Fri 03:44]



* How To Publish org roam notes :org:roam:emacs:

By Defualt org roam notes do not work with ~org-publish~ becuase it doesnt know how to resolve the id links.



** Publish Script
:PROPERTIES:
:ID:       2b069384-79d9-4ed3-bc6e-b766edf526cb
:END:

Preamble header
A simple macro to run code when not in [[help:noninteractive][noninteractive]].

#+begin_src emacs-lisp
(defmacro with-batch (&rest body)
  "Execute BODY only if Emacs is running in batch mode."
  `(when noninteractive
     ,@body))

#+end_src

#+RESULTS:

Package setup for when it is ran as ~--script~.
#+begin_src emacs-lisp
(with-batch
 (progn
   (require 'package)
   (setq package-user-dir (expand-file-name "./.packages"))
   (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                            ("elpa" . "https://elpa.gnu.org/packages/")
                            ("nongnu" . "https://elpa.nongnu.org/nongnu/")))
   (package-initialize)
   (unless package-archive-contents
     (package-refresh-contents))
   (package-install 'htmlize)
   (package-install 'org-roam)
   (package-install 'org-contrib)))
(require 'htmlize) ;; For Code blocks
(require 'find-lisp)
(require 'org)
(load-file "~/.dotfiles/lisp/org-helpers/ox-rss.el")
(require 'ox-publish)
(require 'org-roam-export) ;; Fixes for org roam to work with ox-publish
(require 'ox-rss)



#+end_src

#+RESULTS:

Set the path to the project directory. We set it to  [[help:org-roam-directory][org-roam-directory]].
If it is noninteractive, I make sure to set org-roam-directory.
#+begin_src emacs-lisp
(defvar project-dir "~/Documents/Notes/org/roam"
  "The Path to the Notes")
(defvar project-output-dir "~/Documents/Notes/org/public")
(if (not noninteractive)
    (setq project-dir org-roam-directory)
  (setq org-roam-directory project-dir))
#+end_src

#+RESULTS:

Exclude Spicy Files. My daily is my personal journal which you dont need to read anyways.
#+begin_src emacs-lisp
(defvar banned-files "sunshine/\\|daily/")
#+end_src

#+RESULTS:

Force org to rebuild the cache.[fn:1]
#+begin_src emacs-lisp
(defun jnf/force-org-rebuild-cache ()
  "Rebuild the `org-mode' and `org-roam' cache."
  (interactive)
  (org-id-update-id-locations)
  ;; Note: you may need `org-roam-db-clear-all'
  ;; followed by `org-roam-db-sync'
  (org-roam-db-sync)
  (org-roam-update-org-id-locations))
#+end_src

#+RESULTS:

Rss functions to create a rss feed. I need to hack on it or use an external method/script.[fn:2]
#+begin_src emacs-lisp
(defun rw/format-rss-feed-entry (entry style project)
  "Format ENTRY for the RSS feed.
ENTRY is a file name.  STYLE is either 'list' or 'tree'.
PROJECT is the current project."
  (cond ((not (directory-name-p entry))
         (let* ((file (org-publish--expand-file-name entry project))
                (title (org-publish-find-title entry project))
                (date (format-time-string "%Y-%m-%d" (org-publish-find-date entry project)))
                (link (concat (file-name-sans-extension entry) ".html")))
           (with-temp-buffer
             (insert (format "* [[file:%s][%s]]\n" file title))
             (org-set-property "RSS_PERMALINK" link)
             (org-set-property "PUBDATE" date)
             (insert-file-contents file)
             (buffer-string))))
        ((eq style 'tree)
         ;; Return only last subdir.
         (file-name-nondirectory (directory-file-name entry)))
        (t entry)))

(defun rw/format-rss-feed (title list)
  "Generate RSS feed, as a string.
TITLE is the title of the RSS feed.  LIST is an internal
representation for the files to include, as returned by
`org-list-to-lisp'.  PROJECT is the current project."
  (concat "#+TITLE: " title "\n\n"
          (org-list-to-subtree list 1 '(:icount "" :istart ""))))

(defun rw/org-rss-publish-to-rss (plist filename pub-dir)
  "Publish RSS with PLIST, only when FILENAME is 'rss.org'.
PUB-DIR is when the output will be placed."
  (if (equal "rss.org" (file-name-nondirectory filename))
      (org-rss-publish-to-rss plist filename pub-dir)))



#+end_src

#+RESULTS:


Remove the html-validation.
#+begin_src emacs-lisp
(setq org-html-validation-link nil)
#+end_src

#+RESULTS:

Make Sure we are using timestamps.
#+begin_src emacs-lisp
(setq org-publish-use-timestamps-flag t)
#+end_src

#+RESULTS:

Ensure org-id-files are set.
#+begin_src emacs-lisp
(setq org-id-extra-files
      (find-lisp-find-files project-dir "\.org$"))
#+end_src

#+RESULTS:

#+end_src

#+RESULTS:

I will use my own styles

#+begin_src emacs-lisp
(setq org-html-validation-link nil            ;; Don't show validation link
      org-html-head-include-scripts nil       ;; Use our own scripts
      org-html-head-include-default-style nil ;; Use our own styles
      org-html-head "<link rel=\"stylesheet\" href=\"/static/style.css\" />")
#+end_src

#+RESULTS:

Finally Lets get to the [[help:help:org-publish-project-alist][org-publish-project-alist]].
#+begin_src emacs-lisp
(setq org-publish-project-alist
      (list (list "lostWiki"
                  :recursive t
                  :base-directory project-dir
                  :publishing-directory project-output-dir
                  :base-extension "org"
                  :toc nil
                  :exclude (regexp-opt '("sunshine" "daily" "globalist"))
                  :auto-sitemap t
                  :base-extension "org"
                  :section-numbers nil
                  :publishing-function #'org-html-publish-to-html)


            (list "lostWikiImages"
              :recurse t
              :base-directory project-dir
              :base-extension "png\\|jpg"
              :publishing-directory project-output-dir
              :publishing-function #'org-publish-attachment)
            (list "lost-css"
              :base-directory project-dir
              :base-extension "css"
              :publishing-directory project-output-dir
              :publishing-function #'org-publish-attachment)
            (list "lost-rss"

                  :base-directory project-dir
                  :base-extension "org"
                  :recursive nil
                  :exclude (regexp-opt '("rss.org" "index.org" "404.org" "sunshine" "daily" "sitemap"))
                  :publishing-function #'rw/org-rss-publish-to-rss
                  :publishing-directory project-output-dir
                  :rss-extension "xml"
                  :html-link-home "/index.html"
                  :html-link-use-abs-url t
                  :html-link-org-files-as-html t
                  :auto-sitemap t
                  :sitemap-filename "rss.org"
                  :sitemap-title "The Lost Wiki"
                  :sitemap-style 'list

                  :sitemap-sort-files 'anti-chronologically
                  :sitemap-function #'rw/format-rss-feed
                  :sitemap-format-entry #'rw/format-rss-feed-entry
                  :auto-sitemap t
                  :sitemap-filename "rss.org"
                  :author "lost robot"
                  :email "")))
#+end_src


Ensure the database is set in non-interactive mode.
Also I update the org-id's for org roam.
#+begin_src emacs-lisp
(with-batch
 (setq org-roam-db-location "~/.emacs.d/.local/cache/org-roam.db")
 (org-roam-update-org-id-locations))
#+end_src

Export
#+begin_src emacs-lisp
(with-batch
 (message "Exporting: %s" project-dir)
 (org-publish-all t)
 (message "Export Complete."))
#+end_src

#+RESULTS:

** See also

+ https://gitlab.com/ngm/commonplace/-/blob/master/publish.el#L98
+ https://orgmode.org/manual/Simple-example.html

* Footnotes
[fn:2] https://gitlab.com/to1ne/blog/blob/master/elisp/publish.el#L170-204

[fn:1] https://takeonrules.com/2022/01/11/resolving-an-unable-to-resolve-link-error-for-org-mode-in-emacs/
