:PROPERTIES:
:ID:       fd4435ad-3a8d-4f0b-b44b-a6886d0fc780
:ROAM_TAGS:
:END:
#+title: Common Lisp
#+CREATED: [2022-12-17 12:03:14]
#+LAST_MODIFIED: [2022-12-17 12:03:14]
* What is common lisp?
Common Lisp is the modern, multi-paradigm, high-performance, compiled, ANSI-standardized, most prominent (along with Scheme) descendant of the long-running family of [[id:2bf517d2-698a-44cf-bb5a-5273da53f717][Lisp]] [[id:ecc6c666-530f-4173-9f21-4038677b32ac][Programming Languages]].

Common Lisp is known for being extremely flexible, having excellent support for object oriented programming, and fast prototyping capabilities. It also sports an extremely powerful macro system that allows you to tailor the language to your application, and a flexible run-time environment that allows modification and debugging of running applications (excellent for server-side development and long-running critical software). It is a multi-paradigm programming language that allows you to choose the approach and paradigm according to your application domain.
