:PROPERTIES:
:ID:       982f9f57-4b5d-44b7-bc9b-89b7d977a077
:ROAM_TAGS:
:END:
#+TITLE: Metaprogramming
#+CREATED: [2022-12-17 12:03:14]
#+LAST_MODIFIED: [2023-01-21 Sat 03:14]
+ [[id:af6fae74-d03b-4930-8f39-63becb43efd9][Nim]]


* Metaprogramming in nim
Some notes From Nim in Action
** Generics
Generics allow you to write programs in a style which you do not know the types until the algorithm is called.
It helps you with code duplication.
You can define as many generic types as you want!

Some languages may refer to them as ~parametric polymorphism~ also known as ~templates~


*** Generic Procedures
An example generic procedure from the book

#+begin_src nim :result output
proc myMax[T](a, b: T): T =
  if a < b:
    return b
  else:
    return a
doAssert myMax(5, 10) == 10
doAssert myMax(31.3, 1.23124) == 31.3
#+end_src

The compiler may not be able to infer generic types. You can explicitly set them with square brackets

#+begin_src nim
doAssert myMax[float](5, 10.5) == 10.5
#+end_src


*** Constraining Generics

Constraining generics makes it easier to convey to you and others the meaning of the generic.

An example would be to call myMax with two strings

#+begin_src nim
echo myMax("Hello", "World!")
#+end_src

This will result in an error

**** type classes/concepts

Concepts is also known as a user defined type classs in other languages, are a construct to create requirements that a matched type must satisfy.

Example
#+begin_src nim
type
  Comparable = concept a
    (a < a) is bool
#+end_src
Concepts are created with the ~concept~ keyword, after that is the type identifiers.
In the example the type is matched when a < returns a bool.


*** Templates
Nim's ~templates~ are procedures that produce code. The easily allows you to deal with boilerplate code.
They allow you to inject varibles into the calling scope.
To call a template you just call it like a procedure.

Example from the book

#+begin_src nim
template `!=` (a, b: untyped) =
  not (a == b)
#+end_src

you can define ~!=~ but you would need to define one fo each type or use generarics
An example would be to look at [[id:78157cd5-9681-4a64-b5c7-0f2b415cd446][star intel]] how i used to use function overloading and now i use templates.

**** Code blocks
A code block is a set of statments. passing multiple statements into a procedure into a procecure needs anonmouse functions.
Templates have a sepcial syntax to support more than one statement.

Example from book

#+begin_src nim
import os
template repeat(statements: untyped) =
  while true:
    statements

repeat:
  echo("Hello Templates!")
  sleep(1000)
#+end_src

the statments is replaces with whatever code block is passed. when passed it looks like this

#+begin_src nim
import os
while true:
  echo("Hello Templates!")
  sleep(1000)
#+end_src

NOTE: when a code block is passed, the last parameter always contains it
***** IDEA read on nim's do syntax

**** Untype Versus Typed
+ Untyped: Allows Indentifers that has yet to be delclared.
+ Typed: allows a indentifier that has a type and by concrete type like ~float, int and string~

**** Template hygiene
Templates can define vairbles that can be accessible after the template.
you might not want that and this is called ~template hygiene~.

Example from book

#+begin_src nim
template declareVar(varName: untyped, value: typed) =
  var varName = value
declareVar(foo, 42)
echo(foo)
#+end_src

Calling the template declares a new var becuase the the var is ~injected~ into the calling scope.
Normaly vars are not injected into the scope, unless marked with the ~{.inject.}~ pragma.
Trying to acess a var without that results in error.
