:PROPERTIES:
:ID:       3b87b958-589f-48c9-8b03-c07072642c8d
:ROAM_TAGS:
:END:
#+title: Emacs Lisp
#+CREATED: [2022-12-17 12:03:14]
#+LAST_MODIFIED: [2023-03-27 Mon 16:18]

* Emacs Lisp

Emacs lisp a lisp dialect for confguring Emacs.
Much of emacs is written in elisp, with some of it in C.

** Values
Any value or object has a type. it may not always be readable

There are differnt types in elisp
+ String
+ Numbers (iteger and float)
+ Con cells
+ Arrays/vectors
+ Many more

There are also types that are specific to emacs lisp.

+ Buffers
+ Windows
+ Frames
+ Threads
+ Keymaps
+ And more


** Eval/Form
A form is any value that you can evaluate.
Some examples
+ lists
+ Symbol
+ Other types

Code Examples
#+begin_src emacs-lisp
[ 1 2 (+ 3 4)]
#+end_src

#+RESULTS:
: [1 2 '(+ 3 4)]

** Symbols
A symbol is a object, but does not self eval
A symbol can contail alpha-numeric charecters but others.
When a symbol is evaluated the value is returned with the binding.

** Prefix v infix
Lisp uses prefix notation.
Any expesion that does a function eval, the first element is a function.

** Error Handling

+ [[id:f284c2d8-6777-4ff5-94e1-a928628810d4][elisp errors]]
