:PROPERTIES:
:ID:       af6fae74-d03b-4930-8f39-63becb43efd9
:ROAM_TAGS:
:END:
#+title: Nim
#+SETUPFILE: /home/unseen/Documents/Notes/org/roam/org-setup.org

#+CREATED: [2022-12-17 12:03:14]
#+LAST_MODIFIED: [2023-03-11 Sat 01:33]

* About
Nim is a staticly typed compiled systems language.
It takes inspiration from python, ada and others.

** Features
Taken from https://nim-lang.org/
+ Nim generates native dependency-free executables, not dependent on a virtual machine, which are small and allow easy redistribution.

+ The Nim compiler and the generated executables support all major platforms like Windows, Linux, BSD and macOS.

+ Nim's memory management is deterministic and customizable with destructors and move semantics, inspired by C++ and Rust. It is well-suited for embedded, hard-realtime systems.

+ Modern concepts like zero-overhead iterators and compile-time evaluation of user-defined functions, in combination with the preference of value-based datatypes allocated on the stack, lead to extremely performant code.

+ Support for various backends: it compiles to C, C++ or JavaScript so that Nim can be used for all backend and frontend needs.

+ Nim is self-contained: the compiler and the standard library are implemented in Nim.

+ Nim has a powerful macro system which allows direct manipulation of the AST, offering nearly unlimited opportunities.

+ Macros cannot change Nim's syntax because there is no need for it — the syntax is flexible enough.

+ Modern type system with local type inference, tuples, generics and sum types.

+ Statements are grouped by indentation but can span multiple lines.

+ Genarics



* Notes
+ [[id:982f9f57-4b5d-44b7-bc9b-89b7d977a077][Metaprogramming]]
+ [[id:8a01ff13-6724-4634-b901-074187c32a85][nim android]]
