:PROPERTIES:
:ID:       634d75f8-4fcf-428a-8412-739668673c3c
:END:
#+TITLE: redis
#+SETUPFILE: /home/unseen/Documents/Notes/org/roam/org-setup.org

#+CREATED: [2023-03-28 Tue 16:09]
#+LAST_MODIFIED: [2023-03-30 Thu 16:18]
* Redis :database:db:redis:
Redis is a in memeory key-value dataabase. Since it is a nosql database it can do a number of things.

It is commonly used as a cache system or a task queue.


Redis stands for remote dictionary server.

** Topics
+ [[id:d7ec3a25-ea89-4ab5-ac11-dd4fd05f94a9][redis expiration]]
+
** Storage and Retrieval

Like other key value databases.
All keys are strings.
Data is Accessed by keys.

Keys exists in a "key" space (think database)
Single commands are atomic.


** Data Types
*** String
Normal sequence of bytes. They are binary safe, so they are not null terminated.
*** Hashes
Represents a collection of key val pairs

The command prefixes start with H


** Commands
I will not list all the commands here, just the most used ones

*** SET
Set is used to set a key to a value

#+begin_src shell
set name foo
#+end_src
#+RESULTS:
: OK
*** GET
Get is used to get a key's value
#+begin_src shell
get name
#+end_src

#+RESULTS:
: "foo"
*** Del
Del removes a key
#+begin_src shell
del name
#+end_src
#+RESULTS:
: (integer) 1

*** GETSET
Get a key's value and set a new one
#+begin_src shell
getset name foo
#+end_src
#+RESULTS:
: nil
#+begin_src shell
setset name foo1
#+end_src
#+RESULTS:
: foo
If you ran it one more time you would get foo1
*** SETNX
Set a key if its non existent (is this a lock?)

#+begin_src shell
setnx name bar
#+end_src
#+RESULTS
: (integer) 0

See since name exists it failed to set the key


#+begin_src shell
setnx name1 bar
#+end_src
#+RESULTS
: (integer) 1


** Atomic Commands

A atomic command is one that can take multiple keys and values and do it in a all or fail manner

They operate the same except have a m added to the name
so ~mset~ would be ~set~.

~del~ can take multiple keys


