:PROPERTIES:
:ID:       fd9a2d8d-57c0-4b3f-8760-7f6cd35c3ad6
:END:
#+TITLE: Quasar
#+SETUPFILE: /home/unseen/Documents/Notes/org/roam/org-setup.org
#+CREATED: [2023-06-03 Sat 18:13]
#+LAST_MODIFIED: [2023-06-03 Sat 18:19]
* Quasar :gui:
Quasar is going to be a graphical interface to starintel and more.

Here is a summery of my ideas.
+ Document schema and other systems are already in place, along with bots and other tools.

+ The existing lish shell is easy to build upon and can be helpful.
+ The goal is to create an interface that functions as a graph viewer, similar to Maltego, where nodes can be added, automation can be run, and the graph can be extended.
+ The extensions for the viewer would be implemented in Common Lisp.
+ One example of a transform is a "port scan" on a host, which adds children nodes with port numbers, leveraging tools like Nmap.
+ Machines could be similar to transforms but with additional functions, such as running FFuF on HTTP.
+ Automating everything may not be the best approach, and the focus is more on the transform idea.
+ The Starintel project could serve as a data source for OSINT (Open-Source Intelligence) tasks.
+ An embedded database is being developed that could replace CouchDB and improve performance, likely built on top of LMDB.
+ The Lisp shell would be a lightweight one, similar to VSCode, and could also extend the graph.
+ Consideration needs to be given to making the interface user-friendly.
+ An intermediate mode UI, is preferred for speed and efficiency.
+ Right-click actions (transforms) for each type would require predicates that return true and a mapping of types to functions.
+ Functions and user configuration will create new actions and data types, expanding the system's capabilities.


There is alot of stuff I need to work out. This is also sort of like an index for concepts and ideas related to starintel/quasar
