:PROPERTIES:
:ID:       49396868-f7bb-4210-b413-fb25e9a1d414
:ROAM_TAGS:
:END:
#+TITLE: Nix Flakes Tutorial
#+CREATED: [2022-12-17 12:03:14]
#+LAST_MODIFIED: [2022-12-17 12:03:14]

* Part One.
** Problems with nix
Nix files can acess any file in the filesystem, or anything in the $NIX_PATH
like ~/.config/nixpks/config.nix

This is not a good solution becuase it is less reproducible

Nix based project are also not easy to share with users.

** What is a flake?
a flake is a source tree that has a flake.nix.

Flakes can depend on other flakes with a flake.lock to ensure reproducible eval.


** Flake example

Here is a simple unix package named *dwarffs*. Its repo is [[https://github.com/edolstra/dwarffs][Here]].
It contains a flake.nix file so it is a flake.
you can install this flake like this:

#+begin_src shell
nix shell github:edolstra/dwarffs --command dwarffs --version
#+end_src

#+RESULTS:
: fusermount version: 2.9.9

Installing a flake like above will only grab the latest version.

***NOTE***: in the aricle the output for the command was so. this shows why you should pin a commit hash!!
#+begin_example
dwarffs 0.1.20200406.cd7955a
#+end_example

***NOTE**: the mentioned commit no longer exists
#+begin_src shell
nix shell github:edolstra/dwarffs/cd7955af31698c571c30b7a0f78e59fd624d0229  --command dwarffs --version
#+end_src

Metadata from flaks can be retrived like this.
#+begin_src shell :results output replace
nix flake metadata github:edolstra/dwarffs
#+end_src

#+RESULTS:
#+begin_example
[1mResolved URL:[0m  github:edolstra/dwarffs
[1mLocked URL:[0m    github:edolstra/dwarffs/e768ce3239156de05f7ff3210d86a80762730f30
[1mDescription:[0m   A filesystem that fetches DWARF debug info from the Internet on demand
[1mPath:[0m          /nix/store/42y672k0alswm1wsp7dixx0q0imrv8y2-source
[1mRevision:[0m      e768ce3239156de05f7ff3210d86a80762730f30
[1mLast modified:[0m 2022-03-06 04:51:03
[1mInputs:[0m
├───[1mnix[0m: github:NixOS/nix/b09baf690bb00125805a02e0feae9636b2114599
│   ├───[1mlowdown-src[0m: github:kristapsdz/lowdown/d2c2b44ff6c27b936ec27358a2653caaef8f73b8
│   ├───[1mnixpkgs[0m: github:NixOS/nixpkgs/82891b5e2c2359d7e58d08849e4c89511ab94234
│   └───[1mnixpkgs-regression[0m: github:NixOS/nixpkgs/215d4d0fd80ca5163643b03a33fde804a29cc1e2
└───[1mnixpkgs[0m follows input 'nix/nixpkgs'
#+end_example

Flake outputs can be shown with

#+begin_src shell :results output replace
nix flake show github:edolstra/dwarffs
#+end_src

#+RESULTS:
#+begin_example
[1mgithub:edolstra/dwarffs/e768ce3239156de05f7ff3210d86a80762730f30[0m
[32;1m├───[0m[1mchecks[0m
[32;1m│   ├───[0m[1maarch64-linux[0m
[32;1m│   │   ├───[0m[1mbuild[0m: derivation 'dwarffs-0.1.20220306.e768ce3'
[32;1m│   │   └───[0m[1mtest[0m: derivation 'vm-test-run-unnamed'
[32;1m│   ├───[0m[1mi686-linux[0m
[32;1m│   │   ├───[0m[1mbuild[0m: derivation 'dwarffs-0.1.20220306.e768ce3'
[32;1m│   │   └───[0m[1mtest[0m: derivation 'vm-test-run-unnamed'
[32;1m│   └───[0m[1mx86_64-linux[0m
[32;1m│       ├───[0m[1mbuild[0m: derivation 'dwarffs-0.1.20220306.e768ce3'
[32;1m│       └───[0m[1mtest[0m: derivation 'vm-test-run-unnamed'
[32;1m├───[0m[1mdefaultPackage[0m
[32;1m│   ├───[0m[1maarch64-linux[0m: package 'dwarffs-0.1.20220306.e768ce3'
[32;1m│   ├───[0m[1mi686-linux[0m: package 'dwarffs-0.1.20220306.e768ce3'
[32;1m│   └───[0m[1mx86_64-linux[0m: package 'dwarffs-0.1.20220306.e768ce3'
[32;1m├───[0m[1mnixosModules[0m
[32;1m│   └───[0m[1mdwarffs[0m: [35;1mNixOS module[0m
[32;1m└───[0m[1moverlay[0m: [35;1mNixpkgs overlay[0m
#+end_example

* Part Two.
** Nix eval is slow
Nix is a interpeted functional language.
In order for it to get information about the packages it needs to evaluate 1000s of nix evaluations.

Example of nix-emv -qa

#+begin_src sh
time nix-env -qa
#+end_src

This is ok for one off use but using it for scripts is slow becuase of the delay.

** Caching nix-env
there is a replacement for nix-env -qa for and its called nix-search.

** Flakes wich caching
Flake evaluations are fully hermetic. It disslows access to files, envrioment varibles.

Nix flakes cache is a sqlite database that stores the output attributes of flakes.

The first run fills it but any run after is much faster

The cache looks like this

#+begin_src shell :results output replace
sqlite3 ~/.cache/nix/eval-cache-v2/0eb2bf36c7deffb8ac2442c6115e21de072901b894ee4b8e4c17a86f89e05350.sqlite .dump
#+end_src

#+RESULTS:
#+begin_example
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Attributes (
    parent      integer not null,
    name        text,
    type        integer not null,
    value       text,
    context     text,
    primary key (parent, name)
);
INSERT INTO Attributes VALUES(0,'',0,NULL,NULL);
INSERT INTO Attributes VALUES(1,'devShells',3,NULL,NULL);
INSERT INTO Attributes VALUES(1,'packages',3,NULL,NULL);
INSERT INTO Attributes VALUES(1,'legacyPackages',3,NULL,NULL);
INSERT INTO Attributes VALUES(1,'devShell',0,NULL,NULL);
INSERT INTO Attributes VALUES(5,'x86_64-linux',0,NULL,NULL);
INSERT INTO Attributes VALUES(6,'type',2,'derivation',NULL);
INSERT INTO Attributes VALUES(6,'drvPath',0,NULL,NULL);
COMMIT;
#+end_example

the cache stores the attributes that nix shell had to eval.

sqlite db name comes from the contents of the top level flake.

* IDEA Part Three
